package com.starsofocean.music.model;

import java.io.Serializable;

public class Album implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.name
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.pic
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.introduction
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.id
     *
     * @return the value of album.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.id
     *
     * @param id the value for album.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.name
     *
     * @return the value of album.name
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.name
     *
     * @param name the value for album.name
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.pic
     *
     * @return the value of album.pic
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.pic
     *
     * @param pic the value for album.pic
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.introduction
     *
     * @return the value of album.introduction
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.introduction
     *
     * @param introduction the value for album.introduction
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", pic=").append(pic);
        sb.append(", introduction=").append(introduction);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}