package com.starsofocean.music.model;

import java.io.Serializable;

public class CommentParentChildren implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_parent_children.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_parent_children.parent_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_parent_children.children_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long childrenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_parent_children.id
     *
     * @return the value of comment_parent_children.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_parent_children.id
     *
     * @param id the value for comment_parent_children.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_parent_children.parent_id
     *
     * @return the value of comment_parent_children.parent_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_parent_children.parent_id
     *
     * @param parentId the value for comment_parent_children.parent_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_parent_children.children_id
     *
     * @return the value of comment_parent_children.children_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getChildrenId() {
        return childrenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_parent_children.children_id
     *
     * @param childrenId the value for comment_parent_children.children_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setChildrenId(Long childrenId) {
        this.childrenId = childrenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentId=").append(parentId);
        sb.append(", childrenId=").append(childrenId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}