package com.starsofocean.music.model;

import java.io.Serializable;

public class Mylove implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylove.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylove.user_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylove.song_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long songId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylove.mv_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long mvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mylove.album_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mylove
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylove.id
     *
     * @return the value of mylove.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylove.id
     *
     * @param id the value for mylove.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylove.user_id
     *
     * @return the value of mylove.user_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylove.user_id
     *
     * @param userId the value for mylove.user_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylove.song_id
     *
     * @return the value of mylove.song_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylove.song_id
     *
     * @param songId the value for mylove.song_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setSongId(Long songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylove.mv_id
     *
     * @return the value of mylove.mv_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getMvId() {
        return mvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylove.mv_id
     *
     * @param mvId the value for mylove.mv_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setMvId(Long mvId) {
        this.mvId = mvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mylove.album_id
     *
     * @return the value of mylove.album_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mylove.album_id
     *
     * @param albumId the value for mylove.album_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mylove
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", songId=").append(songId);
        sb.append(", mvId=").append(mvId);
        sb.append(", albumId=").append(albumId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}