package com.starsofocean.music.model;

import java.io.Serializable;

public class Singer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singer.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singer.name
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singer.introduction
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singer.pic
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singer.sex
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singer.location
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singer.album_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table singer
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singer.id
     *
     * @return the value of singer.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singer.id
     *
     * @param id the value for singer.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singer.name
     *
     * @return the value of singer.name
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singer.name
     *
     * @param name the value for singer.name
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singer.introduction
     *
     * @return the value of singer.introduction
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singer.introduction
     *
     * @param introduction the value for singer.introduction
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singer.pic
     *
     * @return the value of singer.pic
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singer.pic
     *
     * @param pic the value for singer.pic
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singer.sex
     *
     * @return the value of singer.sex
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singer.sex
     *
     * @param sex the value for singer.sex
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singer.location
     *
     * @return the value of singer.location
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singer.location
     *
     * @param location the value for singer.location
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singer.album_id
     *
     * @return the value of singer.album_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singer.album_id
     *
     * @param albumId the value for singer.album_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singer
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", introduction=").append(introduction);
        sb.append(", pic=").append(pic);
        sb.append(", sex=").append(sex);
        sb.append(", location=").append(location);
        sb.append(", albumId=").append(albumId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}