package com.starsofocean.music.model;

import java.io.Serializable;

public class SongListRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_list_relation.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_list_relation.song_list_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long songListId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song_list_relation.song_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private Long songId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_list_relation.id
     *
     * @return the value of song_list_relation.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_list_relation.id
     *
     * @param id the value for song_list_relation.id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_list_relation.song_list_id
     *
     * @return the value of song_list_relation.song_list_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getSongListId() {
        return songListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_list_relation.song_list_id
     *
     * @param songListId the value for song_list_relation.song_list_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setSongListId(Long songListId) {
        this.songListId = songListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song_list_relation.song_id
     *
     * @return the value of song_list_relation.song_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public Long getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song_list_relation.song_id
     *
     * @param songId the value for song_list_relation.song_id
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    public void setSongId(Long songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", songListId=").append(songListId);
        sb.append(", songId=").append(songId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}