package com.starsofocean.music.mapper;

import com.starsofocean.music.model.Album;
import com.starsofocean.music.model.AlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    long countByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insert(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insertSelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    List<Album> selectByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    Album selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExampleSelective(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExample(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKeySelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKey(Album record);
}