package com.starsofocean.music.mapper;

import com.starsofocean.music.model.CommentParentChildren;
import com.starsofocean.music.model.CommentParentChildrenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentParentChildrenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    long countByExample(CommentParentChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByExample(CommentParentChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insert(CommentParentChildren record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insertSelective(CommentParentChildren record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    List<CommentParentChildren> selectByExample(CommentParentChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    CommentParentChildren selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExampleSelective(@Param("record") CommentParentChildren record, @Param("example") CommentParentChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExample(@Param("record") CommentParentChildren record, @Param("example") CommentParentChildrenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKeySelective(CommentParentChildren record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_parent_children
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKey(CommentParentChildren record);
}