package com.starsofocean.music.mapper;

import com.starsofocean.music.model.Mv;
import com.starsofocean.music.model.MvExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    long countByExample(MvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByExample(MvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insert(Mv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insertSelective(Mv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    List<Mv> selectByExample(MvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    Mv selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExampleSelective(@Param("record") Mv record, @Param("example") MvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExample(@Param("record") Mv record, @Param("example") MvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKeySelective(Mv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mv
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKey(Mv record);
}