package com.starsofocean.music.mapper;

import com.starsofocean.music.model.Song;
import com.starsofocean.music.model.SongExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    long countByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insertSelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    List<Song> selectByExampleWithBLOBs(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    List<Song> selectByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    Song selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExampleSelective(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExampleWithBLOBs(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExample(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKeySelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKeyWithBLOBs(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKey(Song record);
}