package com.starsofocean.music.mapper;

import com.starsofocean.music.model.SongListRelation;
import com.starsofocean.music.model.SongListRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SongListRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    long countByExample(SongListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByExample(SongListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insert(SongListRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int insertSelective(SongListRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    List<SongListRelation> selectByExample(SongListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    SongListRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExampleSelective(@Param("record") SongListRelation record, @Param("example") SongListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByExample(@Param("record") SongListRelation record, @Param("example") SongListRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKeySelective(SongListRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table song_list_relation
     *
     * @mbg.generated Thu Oct 27 23:49:07 HKT 2022
     */
    int updateByPrimaryKey(SongListRelation record);
}